### ISSUE TITLE
Compile error on debian

### ISSUE THREAD

**Issue by neszt** [danvk/performance-boggle#1]
This show the compile error on debian stretch, but i also tried with older releases, without success.

\$ docker run -it --rm debian:stretch
\# apt-get update && apt-get -y upgrade
\# apt-get -y install git make g++
\# cd /usr/src
\# git clone https://github.com/danvk/performance-boggle.git
\# cd performance-boggle
\# make test
g++  -g -Wall -O3 -I. -Iglog-src -Wno-sign-compare  -c -o trie_test.o trie_test.cc
g++  -g -Wall -O3 -I. -Iglog-src -Wno-sign-compare  -c -o trie.o trie.cc
g++   trie_test.o trie.o   -o trie_test
g++  -g -Wall -O3 -I. -Iglog-src -Wno-sign-compare  -c -o 3x3/boggler_test.o 3x3/boggler_test.cc
g++  -g -Wall -O3 -I. -Iglog-src -Wno-sign-compare  -c -o boggle_solver.o boggle_solver.cc
g++  -g -Wall -O3 -I. -Iglog-src -Wno-sign-compare  -c -o 3x3/boggler.o 3x3/boggler.cc
g++  -g -Wall -O3 -I. -Iglog-src -Wno-sign-compare  -c -o 4x4/boggler.o 4x4/boggler.cc
g++  -g -Wall -O3 -I. -Iglog-src -Wno-sign-compare  -c -o 3x4/boggler.o 3x4/boggler.cc
g++  -g -Wall -O3 -I. -Iglog-src -Wno-sign-compare  -c -o gflags/gflags.o gflags/gflags.cc
gflags/gflags.cc:376:40: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
       snprintf(intbuf, sizeof(intbuf), "%"PRId32, VALUE_AS(int32));
                                        ^
gflags/gflags.cc:379:40: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
       snprintf(intbuf, sizeof(intbuf), "%"PRId64, VALUE_AS(int64));
                                        ^
gflags/gflags.cc:382:40: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
       snprintf(intbuf, sizeof(intbuf), "%"PRIu64, VALUE_AS(uint64));
                                        ^
gflags/gflags.cc:479:5: warning: 'int google::{anonymous}::FlagValue::ValueSize() const' defined but not used [-Wunused-function]
 int FlagValue::ValueSize() const {
     ^~~~~~~~~
g++  -g -Wall -O3 -I. -Iglog-src -Wno-sign-compare  -c -o gflags/gflags_reporting.o gflags/gflags_reporting.cc
g++  -g -Wall -O3 -I. -Iglog-src -Wno-sign-compare  -c -o gflags/gflags_completions.o gflags/gflags_completions.cc
g++  -g -Wall -O3 -I. -Iglog-src -Wno-sign-compare  -c -o glog-src/logging.o glog-src/logging.cc
g++  -g -Wall -O3 -I. -Iglog-src -Wno-sign-compare  -c -o glog-src/utilities.o glog-src/utilities.cc
g++  -g -Wall -O3 -I. -Iglog-src -Wno-sign-compare  -c -o glog-src/symbolize.o glog-src/symbolize.cc
glog-src/symbolize.cc:235:24: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
       RAW_LOG(WARNING, "Section name '%s' is too long (%"PRIuS"); "
                        ^
g++  -g -Wall -O3 -I. -Iglog-src -Wno-sign-compare  -c -o glog-src/demangle.o glog-src/demangle.cc
g++  -g -Wall -O3 -I. -Iglog-src -Wno-sign-compare  -c -o glog-src/raw_logging.o glog-src/raw_logging.cc
g++  -g -Wall -O3 -I. -Iglog-src -Wno-sign-compare  -c -o glog-src/vlog_is_on.o glog-src/vlog_is_on.cc
g++  -g -Wall -O3 -I. -Iglog-src -Wno-sign-compare  -c -o glog-src/signalhandler.o glog-src/signalhandler.cc
In file included from glog-src/symbolize.h:58:0,
                 from glog-src/signalhandler.cc:36:
glog-src/signalhandler.cc: In function 'void* google::{anonymous}::GetPC(void*)':
glog-src/config.h:142:37: error: base operand of '->' has non-pointer type 'mcontext_t'
 #define PC_FROM_UCONTEXT uc_mcontext->__ss.__rip
                                     ^
glog-src/signalhandler.cc:75:28: note: in expansion of macro 'PC_FROM_UCONTEXT'
     return (void*)context->PC_FROM_UCONTEXT;
                            ^~~~~~~~~~~~~~~~
<builtin>: recipe for target 'glog-src/signalhandler.o' failed
make: *** [glog-src/signalhandler.o] Error 1

**Comment by danvk** [comment]
This code almost certainly predates C++11. If you have a fix I'd be happy
to merge a PR.

**Comment by danvk** [comment]
(And the Dockerfile)

**Comment by neszt** [comment]
Ok, PR created.
